"""Add M5 LLM fields

Revision ID: 0ecf2869f3a8
Revises: 5044c4f02ba7
Create Date: 2026-09-30 21:16:04.555352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ecf2869f3a8'
down_revision: Union[str, Sequence[str], None] = '5044c4f02ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('input_type', sa.String(), nullable=True))
    op.add_column('analyses', sa.Column('original_filename', sa.String(), nullable=True))
    op.add_column('analyses', sa.Column('llm_confidence', sa.Float(), nullable=True))
    op.add_column('analyses', sa.Column('llm_reasoning', sa.String(), nullable=True))
    op.add_column('analyses', sa.Column('processing_status', sa.String(), nullable=True))
    op.add_column('analyses', sa.Column('model_version', sa.String(), nullable=True))
    op.add_column('analyses', sa.Column('rag_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'rag_version')
    op.drop_column('analyses', 'model_version')
    op.drop_column('analyses', 'processing_status')
    op.drop_column('analyses', 'llm_reasoning')
    op.drop_column('analyses', 'llm_confidence')
    op.drop_column('analyses', 'original_filename')
    op.drop_column('analyses', 'input_type')
    # ### end Alembic commands ###
