"""Add settings fields

Revision ID: 3ad28dd9654e
Revises: ede2c64c6a84
Create Date: 2026-09-30 22:27:04.792822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad28dd9654e'
down_revision: Union[str, Sequence[str], None] = 'ede2c64c6a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('community_updates', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('marketing_updates', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'marketing_updates')
    op.drop_column('users', 'community_updates')
    op.drop_column('users', 'email_notifications')
    op.drop_column('users', 'two_factor_enabled')
    # ### end Alembic commands ###
