"""Add M8 Escalation and Jira integration models

Revision ID: 4654f552bab5
Revises: 971a0f3899d1
Create Date: 2026-10-01 10:57:16.194429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4654f552bab5'
down_revision: Union[str, Sequence[str], None] = '971a0f3899d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('review_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_reviewer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('escalation_reason', sa.String(), nullable=True),
    sa.Column('escalation_reasons_json', sa.JSON(), nullable=True),
    sa.Column('review_decision', sa.String(), nullable=True),
    sa.Column('reviewer_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['assigned_reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_index(op.f('ix_review_cases_id'), 'review_cases', ['id'], unique=False)
    op.create_index(op.f('ix_review_cases_priority'), 'review_cases', ['priority'], unique=False)
    op.create_index(op.f('ix_review_cases_status'), 'review_cases', ['status'], unique=False)
    op.create_table('jira_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_case_id', sa.Integer(), nullable=True),
    sa.Column('jira_issue_id', sa.String(), nullable=True),
    sa.Column('jira_issue_key', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['review_case_id'], ['review_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_case_id')
    )
    op.create_index(op.f('ix_jira_integrations_id'), 'jira_integrations', ['id'], unique=False)
    op.create_table('review_case_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_case_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('previous_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['review_case_id'], ['review_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_case_events_id'), 'review_case_events', ['id'], unique=False)
    op.create_index(op.f('ix_review_case_events_review_case_id'), 'review_case_events', ['review_case_id'], unique=False)
    op.add_column('knowledge_entries', sa.Column('source_type', sa.String(), nullable=True))
    op.add_column('knowledge_entries', sa.Column('source_reference', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_entries', 'source_reference')
    op.drop_column('knowledge_entries', 'source_type')
    op.drop_index(op.f('ix_review_case_events_review_case_id'), table_name='review_case_events')
    op.drop_index(op.f('ix_review_case_events_id'), table_name='review_case_events')
    op.drop_table('review_case_events')
    op.drop_index(op.f('ix_jira_integrations_id'), table_name='jira_integrations')
    op.drop_table('jira_integrations')
    op.drop_index(op.f('ix_review_cases_status'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_priority'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_id'), table_name='review_cases')
    op.drop_table('review_cases')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
