"""add_analysis_performance

Revision ID: 971a0f3899d1
Revises: 3ad28dd9654e
Create Date: 2026-10-01 10:16:34.223797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971a0f3899d1'
down_revision: Union[str, Sequence[str], None] = '3ad28dd9654e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('input_type', sa.String(), nullable=True),
    sa.Column('extraction_ms', sa.Float(), nullable=True),
    sa.Column('preprocessing_ms', sa.Float(), nullable=True),
    sa.Column('ml_ms', sa.Float(), nullable=True),
    sa.Column('embedding_ms', sa.Float(), nullable=True),
    sa.Column('rag_ms', sa.Float(), nullable=True),
    sa.Column('llm_ms', sa.Float(), nullable=True),
    sa.Column('risk_engine_ms', sa.Float(), nullable=True),
    sa.Column('database_ms', sa.Float(), nullable=True),
    sa.Column('total_ms', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_performance_id'), 'analysis_performance', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_performance_id'), table_name='analysis_performance')
    op.drop_table('analysis_performance')
    # ### end Alembic commands ###
