"""Add original_text to Analysis

Revision ID: ede2c64c6a84
Revises: 0ecf2869f3a8
Create Date: 2026-09-30 22:03:50.886157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede2c64c6a84'
down_revision: Union[str, Sequence[str], None] = '0ecf2869f3a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('original_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'original_text')
    # ### end Alembic commands ###
